spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pets?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 123456
  servlet:
    multipart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

cloud:
  aws:
    credentials:
      profile-name: local_pets
    s3:
      bucket-name: petsbucket


